name: webspark_test
description: webspark_test
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: ^3.19.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  go_router: ^14.3.0
  injectable: ^2.4.0
  get_it: ^8.0.2
  formz: ^0.8.0
  freezed_annotation: ^3.0.0
  
  domain:
    path: ./packages/domain

  data:
    path: ./packages/data

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_native_splash: ^2.3.10
  injectable_generator: ^2.4.0
  freezed: ^3.0.6

dependency_overrides:
  meta: ^1.12.0

flutter:
  uses-material-design: true
  generate: true
  
flutter_gen:
  output: lib/app/
  integrations:
    flutter_svg: true