include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    always_use_package_imports: false
    directives_ordering: false
    lines_longer_than_80_chars: false
    avoid_positional_boolean_parameters: false
    require_trailing_commas: false

analyzer:
  errors:
    one_member_abstracts: ignore
  exclude:
    - "**/*.g.dart"
